version: '3'
services:
  #PHP App
  nvision:
    build:
      context: .
      dockerfile: config/dockerfile
    image: christexe/php:8.1-fpm-alpine
    container_name: php_nvision
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: nvision
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./project/:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_nvision
    restart: unless-stopped
    tty: true
    ports:
      - "90:90"
    volumes:
      - ./project/:/var/www/html
      - ./config/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
  #MySQL Service
  db2:
    image: mysql:5.7.22
    container_name: db_nvision
    restart: unless-stopped
    tty: true
    ports:
      - "3318:3318"
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: nvision
      MYSQL_ROOT_PASSWORD: nvision123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - default

#Docker Networks
networks:
  default:
    name: intranet
    external: false
